// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcY5JM2DlV8QaAex51aI7gkJMLXsIa5Kc',
    appId: '1:534461420955:web:06863e103b62963ac7bd3e',
    messagingSenderId: '534461420955',
    projectId: 'materia-match-app',
    authDomain: 'materia-match-app.firebaseapp.com',
    storageBucket: 'materia-match-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUfjNEIJJeGje4pxB3LIp63GLm-3VmSMc',
    appId: '1:534461420955:android:6ae51e23e9db26b9c7bd3e',
    messagingSenderId: '534461420955',
    projectId: 'materia-match-app',
    storageBucket: 'materia-match-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfE227yg-vVqyeD2MkbsZhwu3BzYWr0Dc',
    appId: '1:534461420955:ios:5ca767bcd86bc879c7bd3e',
    messagingSenderId: '534461420955',
    projectId: 'materia-match-app',
    storageBucket: 'materia-match-app.firebasestorage.app',
    iosBundleId: 'com.example.materiaMatchApp',
  );

}